baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Computational Engineering Laboratory, Faculty of Engineering, University of Rijeka'

# Theme
theme = "LoveIt"

# Main menu
[menu]

  # [[menu.main]]
  #   name = "Home"
  #   url  = "/"
  #   weight = 1

  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Staff"
    url  = "/staff/"
    weight = 2

  [[menu.main]]
    name = "Courses"
    url  = "/courses/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Publications"
    url  = "/publications/"
    weight = 5

  [[menu.main]]
    name = "Software"
    url  = "/software/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  study = "studies"

[params]
  disableMermaid = true # Disable mermaid
  mainSections = ["posts", "courses"]
  ShowMenu = true
  homeTitle = "Computational Engineering Laboratory homepage"
  title = "Computational Engineering Laboratory"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Computational Engineering Laboratory"

  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]

  # site default theme ["auto", "light", "dark"]
  defaultTheme = "light"
  customCSS = ["css/custom.css"]

  # Author config
  # 作者配置
  [params.author]
    name = "xxxx"
    email = ""
    link = ""

  # Header config
  # 页面头部导航栏配置
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    # 页面头部导航栏标题配置
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      logo = "https://riteh.uniri.hr/wp-content/uploads/2024/06/riteh-znak-plavo.svg"
      # title name
      # 标题名称
      name = "Computational Engineering Lab"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = "  "
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = true


  # Footer config
  # 页面底部信息配置
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = "Computational Engineering Laboratory, Faculty of Engineering, University of Rijeka</br>"
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = false
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = false
    # site creation time
    # 网站创立年份
    since = 2025
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= ''


  # Home page config
  # 主页信息设置
  [params.home]
    # amount of RSS pages
    # RSS 文章数目
    rss = 10
    disableHero = true
    # Home page profile
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = ""
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title = "Welcome to Computational Engineering Laboratory web site"
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "Faculty of Engineering, University of Rijeka"
      # whether to use typeit animation for subtitle
      # 是否为副标题显示打字机动画
      typeit = false
      # whether to show social links
      # 是否显示社交账号
      social = true
      # disclaimer (HTML format is supported)
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # Home page posts
    # 主页文章列表
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      # 主页每页显示文章数量
      paginate = 6

    [params.home.courses]
      enable = false

